// Drives the plugin's REAL syncPull/syncPush over HTTPS against the deployed Character Intake script, using a
// character sheet generated by the live form (path in argv[2]). Proves the transport (POST + Apps Script's
// redirect, JSON parsing) works end to end. Leaves a ZZSTRESS row in the Sheet; wipe it from the Apps Script editor.
"use strict";
const fs = require("fs");
const assert = require("assert");
const src = fs.readFileSync("C:/Users/glenh/My-Little-Guy/main.js", "utf8");
const obsidian = new Proxy({}, { get: (_t, k) => (k === "Platform" ? { isMobile: false } : class {}) });
const mod = { exports: {} };
new Function("module", "exports", "require", src)(mod, mod.exports, (n) => (n === "obsidian" ? obsidian : require(n)));
const C = mod.exports.__sync;

// the same shape Obsidian's requestUrl gives the plugin; fetch follows the redirect like requestUrl does
const request = async ({ url, method, body, contentType }) => {
	const r = await fetch(url, { method, body, headers: contentType ? { "Content-Type": contentType } : undefined, redirect: "follow" });
	const text = await r.text();
	let json = null; try { json = JSON.parse(text); } catch (e) { /* leave null */ }
	return { status: r.status, json };
};

(async () => {
	const info = C.parseSyncInfo(fs.readFileSync(process.argv[2], "utf8"));
	assert(info, "no kadria-sync comment in " + process.argv[2]);
	const log = (ok, m) => console.log((ok ? "  PASS " : "  FAIL ") + m);

	const first = await C.syncPull(request, info);
	log(first.ok && first.playerOwned && first.playerOwned.hp > 0, `pull over HTTPS: ok, HP ${first.playerOwned && first.playerOwned.hp}, level ${first.character && first.character.level}`);

	const fm = { hp: 4, hp_max: first.playerOwned.hpMax, ac: first.playerOwned.ac, gold: 17.5, inventory: [{ name: "rope", qty: 2 }, { name: "a torch", qty: 1 }], spell_slots: C.normSlots({ 1: { used: 1, max: 2 } }) };
	const push = await C.syncPush(request, info, C.buildPushFields(fm));
	log(push.ok && push.updated.length === 6 && push.rejected.length === 0, `push over HTTPS (POST + redirect): updated ${JSON.stringify(push.updated)}, rejected ${JSON.stringify(push.rejected)}`);

	const back = await C.syncPull(request, info);
	const restored = {}; C.applyPlayerOwned(restored, back.playerOwned);
	log(restored.hp === 4 && restored.gold === 17.5 && JSON.stringify(restored.inventory) === JSON.stringify(fm.inventory) && JSON.stringify(restored.spell_slots) === JSON.stringify(fm.spell_slots),
		`pull returns exactly what was pushed (hp ${restored.hp}, gold ${restored.gold}, ${restored.inventory.length} items, slots ${JSON.stringify(restored.spell_slots)})`);
	log(!!back.lastPushed, `lastPushed stamped: ${back.lastPushed}`);

	const bad = await C.syncPush(request, { ...info, token: "wrong" }, { hp: 1 });
	log(bad.ok === false, "a wrong token is refused over HTTPS");
	const evil = await C.syncPush(request, info, { party: "Hijack", level: 20 });
	log(evil.ok && evil.updated.length === 0 && evil.rejected.length === 2, "DM-owned / form-owned fields are rejected over HTTPS");
})().catch((e) => { console.error(e); process.exit(1); });
